AWSTemplateFormatVersion: 2010-09-09
Description: Provisions HIPAA Ready Environment in AWS - Staging (qs-1rabh51jr)
Metadata:
  Identifier:
    Value: main
  Input:
    Description: Input of all required parameters in nested stacks
  Output:
    Description: N/A
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Staging VPC configuration
      Parameters:
      - StagingVPCCIDRBlock
      - StagingVPCPrivateSubnet1
      - StagingVPCPrivateSubnet2
      - StagingVPCFlowLogLogGroupRetention
    ParameterLabels:
      StagingVPCCIDRBlock:
        default: Staging VPC CIDR block
      StagingVPCPrivateSubnet1:
        default: Staging Subnet 1 CIDR block
      StagingVPCPrivateSubnet2:
        default: Staging Subnet 2 CIDR block
      StagingVPCFlowLogLogGroupRetention:
        default: Staging VPC log group retention days
Parameters:
  StagingVPCCIDRBlock:
    Type: String
    Description: Staging VPC CIDR block.
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
  StagingVPCPrivateSubnet1:
    Type: String
    Description: Staging VPC private subnet 1.
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
  StagingVPCPrivateSubnet2:
    Type: String
    Description: Staging VPC private subnet 2.
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
  StagingVPCFlowLogLogGroupRetention:
    Type: String
    Description: Staging VPC flow logs log group retention days.
Resources:
  StagingVPCFlowLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      RetentionInDays: !Ref StagingVPCFlowLogLogGroupRetention
  StagingFlowLogsRole:
#    Metadata:
#      cfn-lint: { config: { ignore_checks: [ EIAMPolicyWildcardResource, EIAMPolicyActionWildcard ], ignore_reasons: [ EIAMPolicyWildcardResource: "Requires full access to function", EIAMPolicyActionWildcard: "Required for proper function" ] } }
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowFlowLogs
            Effect: Allow
            Principal:
              Service: vpc-flow-logs.amazonaws.com
            Action: 'sts:AssumeRole'
      Description: Staging Flow Logs Role
      Path: /
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 'logs:DescribeLogGroups'
                  - 'logs:DescribeLogStreams'
                Resource: !Sub '${StagingVPCFlowLogGroup.Arn}'
          PolicyName: Staging-Flow-Logs-Role
      Tags:
        - Key: Name
          Value: Staging VPC Flow Logs Role
        - Key: Purpose
          Value: Networking
  StagingVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref StagingVPCCIDRBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: Staging VPC
        - Key: Purpose
          Value: Networking
    DependsOn:
      - StagingVPCFlowLogGroup
  StagingVPCFlowLogs:
    Type: 'AWS::EC2::FlowLog'
    Properties:
      ResourceId: !Ref StagingVPC
      ResourceType: VPC
      TrafficType: ALL
      DeliverLogsPermissionArn: !GetAtt 
        - StagingFlowLogsRole
        - Arn
      LogDestinationType: cloud-watch-logs
      LogGroupName: !Ref StagingVPCFlowLogGroup
      Tags:
        - Key: Name
          Value: Staging VPC Flow Logs
        - Key: Purpose
          Value: Networking
  StagingPrivateSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: !Ref StagingVPCPrivateSubnet1
      VpcId: !Ref StagingVPC
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Staging Core Subnet 1
        - Key: Purpose
          Value: Networking
  StagingPrivateSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: !Ref StagingVPCPrivateSubnet2
      VpcId: !Ref StagingVPC
      AvailabilityZone: !Select [ 1, !GetAZs "" ]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Staging Core Subnet 2
        - Key: Purpose
          Value: Networking
  StagingPrivateRouteTable1:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref StagingVPC
      Tags:
        - Key: Name
          Value: Staging VPC Private Route Table 1
        - Key: Purpose
          Value: Networking
  StagingCore1RouteAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref StagingPrivateRouteTable1
      SubnetId: !Ref StagingPrivateSubnet1
  StagingCore2RouteAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref StagingPrivateRouteTable1
      SubnetId: !Ref StagingPrivateSubnet2
Outputs:
  StagingPrivateSubnet1:
    Value: !Ref StagingPrivateSubnet1
  StagingPrivateSubnet2:
    Value: !Ref StagingPrivateSubnet2
  StagingVPC:
    Value: !Ref StagingVPC
  StagingPrivateRouteTable1:
    Value: !Ref StagingPrivateRouteTable1
  Help:
    Description: For assistance or questions regarding this quickstart please email compliance-accelerator@amazon.com
    Value: ''
